name: projetflutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloudinary_public: ^0.23.1
  dio: ^5.7.0
  flutter_map: ^7.0.2
  get: ^4.6.6
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  logger: ^2.5.0
  path: ^1.9.0
  persistent_shopping_cart: ^0.0.7
  sliver_tools: ^0.2.12
  sqflite: ^2.4.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  # Mise à jour vers la dernière version

flutter:
  uses-material-design: true